#!/usr/bin/env bash
shopt -s globstar
shopt -s nullglob
shopt -s extglob

coredir="$(realpath "$0")"; 
coredir="${coredir%/*/*}"
releng="$coredir/org.jcryptool.releng"
product="$coredir/org.jcryptool.product"


rm -rf ~/.m2
mkdir ~/.m2

cd "$releng"

mvn clean package 2>&1 1>/tmp/mavenbuild$RANDOM.log || { echo "build problem"; exit 2; }

target="$product/target/products/jcryptool-1.0.0-linux.gtk.x86_64.tar.gz"
linuxarchive="$(echo "$product/target/products"/*/linux/**/plugins/org.eclipse.help.ui_*.jar)"

[[ -z "$linuxarchive" ]] && { echo "linux jar helpui plugin file not found" >&2; exit 1; }

set -euo pipefail

# ls -la "$linuxarchive"
jar -tf "$linuxarchive" | grep 'ThisIsCustomBuilt' >/dev/null && \
    { echo success: org.jcryptool.help.ui is the patched one >&2; exit 0; } || \
    { echo "failure: org.jcryptool.help.ui does not contain ThisIsCustomBuilt.class"; exit 1; }
