//-----BEGIN DISCLAIMER-----
/*******************************************************************************
* Copyright (c) 2010 JCrypTool Team and Contributors
*
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*******************************************************************************/
//-----END DISCLAIMER-----
package org.jcryptool.visual.viterbi.algorithm;

/**
 *
 * This interface provides methods for combining strings and characters. The
 * substract method inverts the add method.
 *
 * The algorithm will work as long as the implementation follows these rules:
 *
 * x = add(a,b)
 *
 * (a == substract(x,b)) must be true
 *
 * (b == substract(x,a)) must be true
 *
 * @author Georg Chalupar, Niederwieser Martin, Scheuchenpflug Simon
 */

public interface Combination {

	/**
	 * Combines two strings.
	 *
	 * @param a
	 * @param b
	 *
	 * @return solution
	 */

	public String add(String a, String b);

	/**
	 * Subtracts sting b from string a.
	 *
	 * @param a
	 * @param b
	 * @return solution
	 */

	public String subtract(String a, String b);

	/**
	 * Adds two characters.
	 *
	 * @param char a
	 * @param char b
	 * @return solution
	 */

	public char add(char a, char b);

	/**
	 * Subtracts string b from string a.
	 *
	 * @param a
	 * @param b
	 * @return solution
	 */

	/**
	 * Calculates last position until two equal strings could generate the given ciphertext
	 * @param cipher a ciphertext generated by combining two plaintexts
	 */
	public char subtract(char a, char b);

	public int getMaxDuplicatePathLength(String cipher);
}
