// -----BEGIN DISCLAIMER-----
/*******************************************************************************
 * Copyright (c) 2013, 2014 JCrypTool Team and Contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
// -----END DISCLAIMER-----
package org.jcryptool.visual.sigVerification.ui.view;

import java.util.Date;

import org.eclipse.core.commands.AbstractHandler;
import org.eclipse.core.commands.Command;
import org.eclipse.core.commands.CommandManager;
import org.eclipse.core.commands.ExecutionEvent;
import org.eclipse.jface.action.IContributionManager;
import org.eclipse.jface.action.IToolBarManager;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.ModifyEvent;
import org.eclipse.swt.events.ModifyListener;
import org.eclipse.swt.events.PaintEvent;
import org.eclipse.swt.events.PaintListener;
import org.eclipse.swt.events.SelectionAdapter;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.layout.RowLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Text;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.commands.ICommandService;
import org.eclipse.ui.menus.CommandContributionItem;
import org.eclipse.ui.menus.CommandContributionItemParameter;
import org.eclipse.wb.swt.SWTResourceManager;
import org.jcryptool.core.logging.utils.LogUtil;
import org.jcryptool.visual.sigVerification.Messages;
import org.jcryptool.visual.sigVerification.SigVerificationPlugin;
import org.jcryptool.visual.sigVerification.cert.CertGeneration;

/**
 * This class contains all the code required for the design and functionality of the verification
 * model view.
 *
 */
public class ModelComposite extends Composite {
    private Text lblGeneralDescription;
    private Text lblHeader;
    private Button btnShellM;
    private Button btnChainM;
    private Label lblRoot;
    private Label lbllevel2;
    private Label lbllevel3;
    private Text lblrootChoose;
    private Text lbllevel2Choose;
    private Text lbllevel3Choose;
    private Button btnNewResult;
    private Text lblChoose;
    private CertGeneration Certificates;
    private Text textValidDate;
	private String now;
	private String dateRoot;
	private String dateLevel2;
	private String dateUser;
	private Date temp;
	private Date changeTest;
	private Date changeRoot;
	private Date changeLevel2;
	private Date changeUser;
	private Group mainGroup;
	private int status = 0; //0: not checked yet, 1: valid, 2: not valid
	private Composite resultComp;
	private SigVerView sigVerView;


    public ModelComposite(final Composite parent, final int style, final SigVerView sigVerView) {
        super(parent, SWT.NONE);
        this.sigVerView = sigVerView;
        setBackground(SWTResourceManager.getColor(SWT.COLOR_WIDGET_BACKGROUND));
        createContents(parent);
        createActions();
    }
    
    protected void addResetIconHandler() {
        // Adds reset button to the Toolbar
        AbstractHandler resetHandler = new AbstractHandler() {
	       	public Object execute(ExecutionEvent event) {
	       		reset();
	       		return null;
	       	}
        };
        defineCommand(sigVerView.resetCommandId, "Reset", resetHandler);
    }

    private void defineCommand(final String commandId, final String name, AbstractHandler handler) {
        ICommandService commandService = (ICommandService)PlatformUI.getWorkbench().getService(ICommandService.class);
    	Command command = commandService.getCommand(commandId);
    	command.define(name,  null, commandService.getCategory(CommandManager.AUTOGENERATED_CATEGORY_ID));
    	command.setHandler(handler);
    }

    /**
     * Create contents of the application window.
     *
     * @param parent
     */
    private void createContents(final Composite parent) {
        parent.setFont(SWTResourceManager.getFont("Segoe UI", 12, SWT.BOLD));
        Color white = SWTResourceManager.getColor(255, 255, 255);
        setLayout(new GridLayout());

        Certificates = new CertGeneration();
        try {//create default certificates
			Certificates.setRoot(Certificates.createCertificate(1));
			Certificates.setLevel2(Certificates.createCertificate(2));
			Certificates.setUser(Certificates.createCertificate(3));
		} catch (Exception e) {
            LogUtil.logError(e);
		}
        
        //HEADER AND DESCRPITION (TOP)
        Composite introComposite = new Composite(this, SWT.NONE);
        introComposite.setBackground(white);
        introComposite.setLayout(new GridLayout());
        introComposite.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, false));
        
		lblHeader = new Text(introComposite, SWT.READ_ONLY | SWT.MULTI | SWT.WRAP);
        lblHeader.setEditable(false);
        lblHeader.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, false));
        lblHeader.setFont(SWTResourceManager.getFont("Segoe UI", 11, SWT.BOLD));
        lblHeader.setText(Messages.ModelComposite_lblHeader);
        lblHeader.setBackground(SWTResourceManager.getColor(255, 255, 255));

        lblGeneralDescription = new Text(introComposite, SWT.READ_ONLY | SWT.MULTI | SWT.WRAP);
        lblGeneralDescription.setEditable(false);
        GridData gd_lblGeneralDescription = new GridData(SWT.FILL, SWT.FILL, true, false);
        gd_lblGeneralDescription.widthHint = 600;
		lblGeneralDescription.setLayoutData(gd_lblGeneralDescription);
		lblGeneralDescription.setBackground(SWTResourceManager.getColor(255, 255, 255));
		lblGeneralDescription.setText(Messages.ModelComposite_description);

		//MAIN GROUP
        mainGroup = new Group(this, SWT.NONE);
        mainGroup.setText(Messages.ModelComposite_lblTitle);
		mainGroup.setBackground(SWTResourceManager.getColor(SWT.COLOR_WIDGET_BACKGROUND));
		GridData gd_mainGroup = new GridData(SWT.FILL, SWT.FILL, true, true);
		gd_mainGroup.widthHint = 600;
		mainGroup.setLayoutData(gd_mainGroup);
		GridLayout gl_mainGroup = new GridLayout(2, true);
		gl_mainGroup.horizontalSpacing = 20;
		mainGroup.setLayout(gl_mainGroup);

		Composite btnComposite = new Composite(mainGroup, SWT.NONE);
		btnComposite.setLayoutData(new GridData(SWT.CENTER, SWT.CENTER, false, false, 2, 1));
		btnComposite.setLayout(new RowLayout());
		
		btnShellM = new Button(btnComposite, SWT.NONE);
		btnShellM.setText(Messages.ModelComposite_btnShellM);

	    btnChainM = new Button(btnComposite, SWT.NONE);
	    btnChainM.setEnabled(false);
	    btnChainM.setText(Messages.ModelComposite_btnChainM);
	    
	    Label lblPlaceholder = new Label(mainGroup, SWT.READ_ONLY);
	    GridData gd_lblPlaceholder = new GridData(SWT.RIGHT, SWT.BOTTOM, false, false);
	    gd_lblPlaceholder.widthHint = 190;
	    lblPlaceholder.setLayoutData(gd_lblPlaceholder);
	    lblPlaceholder.setText(Messages.ModelComposite_certLayer);
	    
	    lblChoose = new Text(mainGroup, SWT.READ_ONLY | SWT.MULTI | SWT.WRAP);
	    lblChoose.setEditable(false);
	    lblChoose.setText(Messages.ModelComposite_Choose);
	    GridData gd_lblChoose = new GridData(SWT.FILL, SWT.FILL, false, false);
	    gd_lblChoose.verticalIndent = 20;
	    lblChoose.setLayoutData(gd_lblChoose);

	    lblRoot = new Label(mainGroup, SWT.NONE);
	    lblRoot.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lblRoot = new GridData(SWT.RIGHT, SWT.FILL, false, false);
	    gd_lblRoot.widthHint = 380;
	    gd_lblRoot.verticalIndent = 10;
	    lblRoot.setLayoutData(gd_lblRoot);
	    lblRoot.setText(Messages.ModelComposite_lblroot);
	    
		temp=Certificates.getRoot().getNotAfter();
		dateRoot=setFormat(temp);
	    
	    lblrootChoose = new Text(mainGroup, SWT.BORDER);
	    lblrootChoose.setEditable(true);
	    lblrootChoose.setText(dateRoot);
	    lblrootChoose.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lblrootChoose = new GridData(SWT.LEFT, SWT.FILL, false, false);
	    gd_lblrootChoose.widthHint = 146;
	    gd_lblrootChoose.verticalIndent = 10; 
	    lblrootChoose.setLayoutData(gd_lblrootChoose);
	    lblrootChoose.setBounds(773, 133, 146, 67);
		
	    lbllevel2 = new Label(mainGroup, SWT.NONE);
	    lbllevel2.setText(Messages.ModelComposite_lbllevel2);
	    lbllevel2.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lbllevel2 = new GridData(SWT.RIGHT, SWT.FILL, false, false);
	    gd_lbllevel2.widthHint = 341;
	    gd_lbllevel2.verticalIndent = 20;
	    lbllevel2.setLayoutData(gd_lbllevel2);
	    
		temp=Certificates.getLevel2().getNotAfter();
		dateLevel2=setFormat(temp);
	    
	    lbllevel2Choose = new Text(mainGroup, SWT.BORDER);
	    lbllevel2Choose.setEditable(true);
	    lbllevel2Choose.setText(dateLevel2);
	    lbllevel2Choose.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lbllevel2Choose = new GridData(SWT.LEFT, SWT.FILL, false, false);
	    gd_lbllevel2Choose.widthHint = 146;
	    gd_lbllevel2Choose.verticalIndent = 20; 
	    lbllevel2Choose.setLayoutData(gd_lbllevel2Choose);
		
	    lbllevel3 = new Label(mainGroup, SWT.NONE);
	    lbllevel3.setText(Messages.ModelComposite_lbllevel3);
	    lbllevel3.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lbllevel3 = new GridData(SWT.RIGHT, SWT.FILL, false, false);
	    gd_lbllevel3.widthHint = 304;
	    gd_lbllevel3.verticalIndent = 20;
	    lbllevel3.setLayoutData(gd_lbllevel3);

		temp=Certificates.getUser().getNotAfter();
		dateUser=setFormat(temp);

	    lbllevel3Choose = new Text(mainGroup, SWT.BORDER);
	    lbllevel3Choose.setEditable(true);
	    lbllevel3Choose.setText(dateUser);
	    lbllevel3Choose.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
	    GridData gd_lbllevel3Choose = new GridData(SWT.LEFT, SWT.FILL, false, false);
	    gd_lbllevel3Choose.widthHint = 146;
	    gd_lbllevel3Choose.verticalIndent = 20; 
	    lbllevel3Choose.setLayoutData(gd_lbllevel3Choose);
	    
	    resultComp = new Composite(mainGroup, SWT.NONE);
	    GridData gd_resultComp = new GridData(SWT.FILL, SWT.FILL, true, false, 2, 1);
	    gd_resultComp.heightHint = 100;
	    resultComp.setLayoutData(gd_resultComp);
	    resultComp.setLayout(new GridLayout(2, false));
	    resultComp.addPaintListener(new PaintListener() {
	    	public void paintControl(PaintEvent e) {
	    		ImageDescriptor idIcon = null;
				if (status == 1) {
                	idIcon = SigVerificationPlugin.getImageDescriptor("icons/gruenerHacken.png"); //$NON-NLS-1$
                }
				else if (status == 2) {
                    idIcon = SigVerificationPlugin.getImageDescriptor("icons/rotesKreuz.png"); //$NON-NLS-1$
                }
				if (idIcon != null) {
		    		GC gc = e.gc;
		    		Rectangle area = resultComp.getClientArea(); // Get the size of the canvas
	                ImageData imdIcon = idIcon.getImageData(100);
	                Image imgIcon = new Image(Display.getCurrent(), imdIcon);
	            	gc.drawImage(imgIcon, (area.width / 2) - 200, 0);
				}
	    	}
	    });

		temp=Certificates.getNow();//default date for validity checks
		now=setFormat(temp); //to string

		textValidDate = new Text(resultComp, SWT.BORDER);
		GridData gd_textValidDate = new GridData(SWT.CENTER, SWT.BOTTOM, true, true, 2, 1);
		gd_textValidDate.widthHint = 146;
		gd_textValidDate.heightHint = 36;
		textValidDate.setLayoutData(gd_textValidDate);
		textValidDate.setEditable(true);
		textValidDate.setText(now);
		textValidDate.setBackground(SWTResourceManager.getColor(SWT.COLOR_LIST_BACKGROUND));
		
		Composite btnComposite2 = new Composite(mainGroup, SWT.NONE);
		btnComposite2.setLayoutData(new GridData(SWT.CENTER, SWT.FILL, false, false, 2, 1));
		btnComposite2.setLayout(new RowLayout());

	    btnNewResult = new Button(btnComposite2, SWT.NONE);
	    btnNewResult.setEnabled(true);
	    btnNewResult.setText(Messages.ModelComposite_btnNewResult);

		Button btnReset = new Button(btnComposite2, SWT.NONE);
		btnReset.addSelectionListener(new SelectionAdapter() {
		    @Override
		    public void widgetSelected(SelectionEvent e) {
		    	reset();
		    }
		});
		btnReset.setText(Messages.ModelComposite_btnReset);
    }

    private void createActions() {
    	//Listener for the new date to valid at
    	 textValidDate.addModifyListener(new ModifyListener() {
             public void modifyText(final ModifyEvent e) {
                 if (textValidDate.getText().length() > 0) {
                 	String temp=new String(textValidDate.getText());
                 	changeTest=toDate(temp);
                 }
             }
         });

    	 //listener for the root validity
    	 lblrootChoose.addModifyListener(new ModifyListener() {
             public void modifyText(final ModifyEvent e) {
                 if (lblrootChoose.getText().length() > 0) {
                 	String temp=new String(lblrootChoose.getText());
                 	changeRoot=toDate(temp);
                 }
             }
         });

    	//listener for the level2 validity
    	 lbllevel2Choose.addModifyListener(new ModifyListener() {
             public void modifyText(final ModifyEvent e) {
                 if (lbllevel2Choose.getText().length() > 0) {
                 	String temp=new String(lbllevel2Choose.getText());
                 	changeLevel2=toDate(temp);
                 }
             }
         });

    	//listener for the user validity
    	 lbllevel3Choose.addModifyListener(new ModifyListener() {
             public void modifyText(final ModifyEvent e) {
                 if (lbllevel3Choose.getText().length() > 0) {
                 	String temp=new String(lbllevel3Choose.getText());
                 	changeUser=toDate(temp);
                 }
             }
         });


     	btnNewResult.addSelectionListener(new SelectionAdapter(){
     		public void widgetSelected(SelectionEvent e) {
     			boolean result = false;

                try {
                    if(changeRoot!=null){//if root has a new validity
              			Certificates.setRoot(Certificates.createCertificateNew(1,changeRoot));
                    }
                    if(changeLevel2!=null){//if level2 has a new validity
              			Certificates.setLevel2(Certificates.createCertificateNew(2,changeLevel2));
                    }
                    if(changeUser!=null){//if user has a new validity
               			Certificates.setUser(Certificates.createCertificateNew(3,changeUser));
                    }

                    if(changeTest!=null){//if the date to validate was changed
                       	result=Certificates.verify(changeTest);
                    }else if(changeTest==null){
                    	result=Certificates.verify(Certificates.getNow());
                    }
                    
                    if (result) status = 1; 
                    else status = 2;
                    resultComp.redraw();

                    if(result==true){//if certificates are valid show green tick
//                    	lblResult1.moveAbove(lblResult2);
//                      lblResult1.setImage(SWTResourceManager.getImage(SigVerComposite.class, "/icons/gruenerHacken.png"));
                    }else{//if certificates are not valid show red cross
//                    	lblResult2.moveAbove(lblResult1);
//                      lblResult2.setImage(SWTResourceManager.getImage(SigVerComposite.class, "/icons/rotesKreuz.png"));
                    }

                 } catch (Exception ex) {
                     LogUtil.logError(SigVerificationPlugin.PLUGIN_ID, ex);
                 }

             }
         });
    }

    /**
     * Converts a date from a String to a Date and requests for the date to be checked
     * @param string - the date (in form of a string) to save
     * @return the string as a date
     */
    @SuppressWarnings("deprecation")
 	private Date toDate(final String string){
     	Date date=new Date();
     	char[] temp=string.toCharArray();
     	int i=1;
     	int day=0,month = 0,year=0;

     	for(;i<string.length();i++){
     		if(i<=1){//day
     			day=((temp[i-1]-48)*10)+(temp[i]-48);
     			date.setDate(day);
     		}else if(i==4){//month
     			month=(((temp[i-1]-48)*10)+(temp[i]-48)-1);
     			date.setMonth(month);
     		}else if(i==9){//year
     			year=(((temp[i-3]-48)*1000)+((temp[i-2]-48)*100)+((temp[i-1]-48)*10)+(temp[i]-48)-1900);
     			date.setYear(year);
     		}
     	}
     	if(checkDate(day,(month+1),(year+1990))!=true){
     		btnNewResult.setEnabled(false);
     	}else{
     		btnNewResult.setEnabled(true);
     	}
     	return date;
     }


    /**
     * checks whether a date is a valid date
     * @param day
     * @param month
     * @param year
     * @return true - if the given date exists
     */
    private boolean checkDate(int day, int month, int year) {
    	boolean result=true;

		if(month<1 || month>12){
			result=false;
		}
		/*months with 31 days*/
		if(month == 1 || month == 3 ||month == 5 ||month == 7 ||month == 8 ||month == 10 ||month == 12){
			if(day <1 || day>31){
				result=false;
			}
		}
		/*months with 30 days*/
		if(month == 4 || month == 6 ||month == 9 ||month == 11){
			if(day <1 || day >30){
				result=false;
			}
		}
		if(month==2 && leapyear(year)==true){
			if(day <1 || day >29){
				result=false;
				}
			}
		if(month==2 && leapyear(year)==false){
			if(day<1 || day >28){
				result=false;
			}
		}
		return result;
	}

    /**
     * checks whether a given year is a leap year
     * @param year
     * @return true if it's a leap year
     */
    public static boolean leapyear(int year){
		if(year%4 == 0 && (year%100 != 0 || year%400 == 0)){
			return true;
		}else{
			return false;
		}
	}

    /**
     * Converts a Date to a String (in order to be displayed on the user interface)
     * @param date to convert
     * @return the String
     */
    @SuppressWarnings("deprecation")
 	public String setFormat(Date date){
     	String result;

     	if(date.getDate()<=9){
     		result="0"+date.getDate()+".";
     	}else{
     		result=date.getDate()+".";
     	}
     	if(date.getMonth()<=9){
     		result+="0"+(date.getMonth()+1)+"."+(date.getYear()+1900)+" ";
     	}else{
     		result+=(date.getMonth()+1)+"."+(date.getYear()+1900)+" ";
     	}

   	  return result;
     }

	/**
	 * resets the certificates to the default certificates
	 * and resets the shown dates
	 */
	private void reset() {
    	btnNewResult.setEnabled(true);
        try {
			Certificates.setRoot(Certificates.createCertificate(1));
			Certificates.setLevel2(Certificates.createCertificate(2));
	 		Certificates.setUser(Certificates.createCertificate(3));

	 		temp=Certificates.getEnd();
			dateRoot=setFormat(temp);
			lblrootChoose.setText(dateRoot);

			dateLevel2=setFormat(temp);
			lbllevel2Choose.setText(dateLevel2);

			dateUser=setFormat(temp);
			lbllevel3Choose.setText(dateUser);
		} catch (Exception e) {
            LogUtil.logError(e);
		}
    }



    /**
     * Create the menu manager.
     *
     * @return the menu manager
     */
    /*
     * @Override protected MenuManager createMenuManager() { MenuManager menuManager = new
     * MenuManager("menu"); return menuManager; }
     */

    /**
     * Create the status line manager.
     *
     * @return the status line manager
     */
    /*
     * @Override protected StatusLineManager createStatusLineManager() { StatusLineManager
     * statusLineManager = new StatusLineManager(); return statusLineManager; } /** Return the
     * initial size of the window.
     */
    /*
     * @Override protected Point getInitialSize() { return new Point(1270, 750); }
     */

}
